In [50]:
import pandas as pd

In [51]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [52]:
df.head(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [53]:
df.tail(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1944,Zimbabwe,2016,3.735,7.984,0.768,54.4,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.0,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.6,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.8,0.643,-0.009,0.789,0.703,0.346

In [54]:
df.sample(5)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1911,Yemen,2011,3.746,8.336,0.663,54.30,0.638,-0.173,0.754,0.503,0.285
1061,Malaysia,2019,5.428,10.252,0.842,67.20,0.916,0.123,0.782,0.834,0.176
376,Comoros,2018,3.973,8.028,0.621,57.20,0.560,0.086,0.794,0.748,0.337
726,Iceland,2013,7.501,10.809,0.967,72.84,0.923,0.306,0.713,0.870,0.156
1334,Palestinian Territories,2015,4.695,8.480,0.766,NaN,0.556,-0.153,0.774,0.594,0.369

In [55]:
df.shape

(1949, 11)

In [56]:
df.dtypes

Country name                         object
year                                  int64
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [57]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [58]:
df[df["Log GDP per capita"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
423,Cuba,2006,5.418,NaN,0.970,68.44,0.281,NaN,NaN,0.647,0.277
436,Cyprus,2020,6.260,NaN,0.806,74.10,0.763,NaN,0.816,0.759,0.284
709,Hong Kong S.A.R. of China,2020,5.295,NaN,0.813,NaN,0.705,NaN,0.380,0.609,0.210
771,Iran,2018,4.278,NaN,0.674,66.00,0.603,NaN,0.703,0.553,0.493
772,Iran,2019,5.006,NaN,0.698,66.30,0.623,NaN,0.728,0.600,0.449
773,Iran,2020,4.865,NaN,0.757,66.60,0.600,NaN,0.710,0.582,0.470
918,Kosovo,2020,6.294,NaN,0.792,NaN,0.880,NaN,0.910,0.726,0.201
1087,Malta,2020,6.157,NaN,0.938,72.20,0.931,NaN,0.675,0.601,0.411
1280,North Cyprus,2012,5.463,NaN,0.871,NaN,0.693,NaN,0.855,0.709,0.405
1281,North Cyprus,2013,5.567,NaN,0.869,NaN,0.775,NaN,0.715,0.622,0.443
1282,North Cyprus,2014,5.786,NaN,0.802,NaN,0.830,NaN,0.692,0.724,0.311
1283,North Cyprus,2015,5.843,NaN,0.791,NaN,0.785,NaN,0.659,0.702,0.319
1284,North Cyprus,2016,5.827,NaN,0.808,NaN,0.796,NaN,0.670,0.644,0.346
1285,North Cyprus,2018,5.608,NaN,0.837,NaN,0.797,NaN,0.614,0.480,0.262
1286,North Cyprus,2019,5.467,NaN,0.803,NaN,0.793,NaN,0.640,0.494,0.296
1337,Palestinian Territories,2018,4.554,NaN,0.819,NaN,0.655,NaN,0.814,0.610,0.419
1338,Palestinian Territories,2019,4.483,NaN,0.833,NaN,0.653,NaN,0.829,0.625,0.400
1559,Somalia,2014,5.528,NaN,0.611,49.60,0.874,NaN,0.456,0.834,0.207
1560,Somalia,2015,5.354,NaN,0.599,50.10,0.968,NaN,0.410,0.901,0.187
1561,Somalia,2016,4.668,NaN,0.594,50.00,0.917,NaN,0.441,0.891,0.193
1562,Somaliland region,2009,4.991,NaN,0.880,NaN,0.746,NaN,0.513,0.819,0.112
1563,Somaliland region,2010,4.657,NaN,0.829,NaN,0.820,NaN,0.471,0.769,0.083
1564,Somaliland region,2011,4.931,NaN,0.788,NaN,0.858,NaN,0.357,0.749,0.122
1565,Somaliland region,2012,5.057,NaN,0.786,NaN,0.758,NaN,0.334,0.735,0.152
1596,South Sudan,2014,3.832,NaN,0.545,49.84,0.567,NaN,0.742,0.614,0.428
1597,South Sudan,2015,4.071,NaN,0.585,50.20,0.512,NaN,0.710,0.586,0.450
1598,South Sudan,2016,2.888,NaN,0.532,50.60,0.440,NaN,0.785,0.615,0.549
1599,South Sudan,2017,2.817,NaN,0.557,51.00,0.456,NaN,0.761,0.586,0.517
1679,Taiwan Province of China,2018,6.467,NaN,0.896,NaN,0.741,NaN,0.736,0.848,0.093
1680,Taiwan Province of China,2019,6.537,NaN,0.893,NaN,0.814,NaN,0.718,0.860,0.093
1681,Taiwan Province of China,2020,6.751,NaN,0.901,NaN,0.799,NaN,0.711,0.845,0.083
1891,Venezuela,2018,5.006,NaN,0.887,66.50,0.611,NaN,0.828,0.759,0.374
1892,Venezuela,2019,5.081,NaN,0.888,66.70,0.626,NaN,0.839,0.761,0.351
1893,Venezuela,2020,4.574,NaN,0.805,66.90,0.612,NaN,0.811,0.722,0.396
1918,Yemen,2018,3.058,NaN,0.789,56.70,0.553,NaN,0.793,0.461,0.315
1919,Yemen,2019,4.197,NaN,0.870,57.50,0.651,NaN,0.798,0.543,0.213

In [60]:
df=df.dropna(subset=["Log GDP per capita"])

In [61]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                    0
Social support                       13
Healthy life expectancy at birth     37
Freedom to make life choices         32
Generosity                           53
Perceptions of corruption           109
Positive affect                      22
Negative affect                      16
dtype: int64

In [62]:
df[df["Social support"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
25,Algeria,2010,5.464,9.287,NaN,64.50,0.593,-0.205,0.618,NaN,NaN
112,Bahrain,2014,6.165,10.783,NaN,67.42,NaN,NaN,NaN,NaN,NaN
294,Canada,2007,7.482,10.739,NaN,71.66,0.930,0.249,0.406,0.872,0.257
466,Djibouti,2010,5.006,7.812,NaN,54.30,0.764,-0.058,0.597,NaN,NaN
925,Kuwait,2014,6.180,10.945,NaN,65.80,NaN,NaN,NaN,NaN,NaN
1164,Morocco,2010,4.383,8.746,NaN,63.50,0.663,-0.162,0.900,NaN,NaN
1310,Oman,2011,6.853,10.382,NaN,65.50,0.916,0.025,NaN,NaN,0.295
1423,Qatar,2010,6.850,11.520,NaN,66.70,NaN,0.104,NaN,NaN,NaN
1426,Qatar,2015,6.375,11.486,NaN,68.30,NaN,NaN,NaN,NaN,NaN
1741,Tunisia,2009,5.025,9.197,NaN,64.96,0.781,-0.119,0.722,NaN,NaN
1814,United Arab Emirates,2014,6.540,11.041,NaN,66.48,NaN,NaN,NaN,NaN,NaN
1837,United States,2007,7.513,10.933,NaN,68.22,0.872,0.197,0.633,0.829,0.232
1905,Vietnam,2017,5.175,8.876,NaN,67.70,NaN,NaN,NaN,NaN,NaN

In [63]:
df[df["Country name"]=="Algeria"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
25,Algeria,2010,5.464,9.287,NaN,64.50,0.593,-0.205,0.618,NaN,NaN
26,Algeria,2011,5.317,9.297,0.810,64.66,0.530,-0.181,0.638,0.550,0.255
27,Algeria,2012,5.605,9.311,0.839,64.82,0.587,-0.172,0.690,0.604,0.230
28,Algeria,2014,6.355,9.335,0.818,65.14,NaN,NaN,NaN,0.626,0.177
29,Algeria,2016,5.341,9.362,0.749,65.50,NaN,NaN,NaN,0.661,0.377
30,Algeria,2017,5.249,9.354,0.807,65.70,0.437,-0.167,0.700,0.642,0.289
31,Algeria,2018,5.043,9.348,0.799,65.90,0.583,-0.146,0.759,0.591,0.293
32,Algeria,2019,4.745,9.337,0.803,66.10,0.385,0.005,0.741,0.585,0.215

In [69]:
df["Social support"]=df["Social support"].fillna(df["Social support"].mean())

In [70]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                    0
Social support                        0
Healthy life expectancy at birth     37
Freedom to make life choices         32
Generosity                           53
Perceptions of corruption           109
Positive affect                      22
Negative affect                      16
dtype: int64

In [71]:
df[df["Healthy life expectancy at birth"].isnull()]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
699,Hong Kong S.A.R. of China,2006,5.511,10.746,0.812,NaN,0.910,0.156,0.356,0.723,0.236
700,Hong Kong S.A.R. of China,2008,5.137,10.816,0.840,NaN,0.922,0.296,0.274,0.719,0.237
701,Hong Kong S.A.R. of China,2009,5.397,10.788,0.835,NaN,0.918,0.308,0.272,0.762,0.210
702,Hong Kong S.A.R. of China,2010,5.643,10.847,0.857,NaN,0.890,0.332,0.256,0.710,0.183
703,Hong Kong S.A.R. of China,2011,5.474,10.887,0.846,NaN,0.894,0.235,0.245,0.734,0.196
704,Hong Kong S.A.R. of China,2012,5.484,10.893,0.826,NaN,0.880,0.222,0.380,0.715,0.183
705,Hong Kong S.A.R. of China,2014,5.458,10.940,0.834,NaN,0.843,0.224,0.423,0.684,0.243
706,Hong Kong S.A.R. of China,2016,5.498,10.970,0.832,NaN,0.800,0.100,0.403,0.664,0.213
707,Hong Kong S.A.R. of China,2017,5.362,11.000,0.831,NaN,0.831,0.140,0.416,0.640,0.201
708,Hong Kong S.A.R. of China,2019,5.659,11.000,0.856,NaN,0.727,0.067,0.432,0.599,0.358
905,Kosovo,2007,5.104,8.928,0.848,NaN,0.381,0.144,0.894,0.655,0.237
906,Kosovo,2008,5.522,8.981,0.884,NaN,NaN,0.090,0.849,NaN,0.318
907,Kosovo,2009,5.891,9.008,0.830,NaN,0.506,0.201,0.968,0.598,0.169
908,Kosovo,2010,5.177,9.033,0.708,NaN,0.451,0.170,0.967,0.695,0.118
909,Kosovo,2011,4.860,9.067,0.759,NaN,0.589,0.004,0.919,0.696,0.124
910,Kosovo,2012,5.640,9.086,0.757,NaN,0.636,0.027,0.950,0.596,0.100
911,Kosovo,2013,6.126,9.113,0.721,NaN,0.568,0.115,0.935,0.692,0.203
912,Kosovo,2014,5.000,9.129,0.706,NaN,0.441,0.012,0.775,0.636,0.206
913,Kosovo,2015,5.077,9.182,0.805,NaN,0.561,0.181,0.851,0.753,0.180
914,Kosovo,2016,5.759,9.228,0.824,NaN,0.827,0.125,0.941,0.704,0.150
915,Kosovo,2017,6.149,9.262,0.792,NaN,0.858,0.117,0.925,0.738,0.186
916,Kosovo,2018,6.392,9.296,0.822,NaN,0.890,0.269,0.922,0.778,0.170
917,Kosovo,2019,6.425,9.339,0.843,NaN,0.841,0.247,0.920,0.749,0.141
1330,Palestinian Territories,2011,4.751,8.474,0.751,NaN,0.522,-0.127,0.750,0.567,0.388
1331,Palestinian Territories,2012,4.647,8.531,0.782,NaN,0.542,-0.153,0.730,0.616,0.379
1332,Palestinian Territories,2013,4.844,8.489,0.761,NaN,0.454,-0.150,0.780,0.594,0.365
1333,Palestinian Territories,2014,4.722,8.457,0.775,NaN,0.657,-0.147,0.804,0.565,0.380
1334,Palestinian Territories,2015,4.695,8.480,0.766,NaN,0.556,-0.153,0.774,0.594,0.369
1335,Palestinian Territories,2016,4.907,8.498,0.818,NaN,0.608,-0.129,0.812,0.593,0.378
1336,Palestinian Territories,2017,4.628,8.485,0.824,NaN,0.632,-0.163,0.831,0.597,0.416
1672,Taiwan Province of China,2011,6.309,10.705,0.863,NaN,0.761,0.035,0.755,0.827,0.112
1673,Taiwan Province of China,2012,6.126,10.716,0.825,NaN,0.698,0.022,0.803,0.821,0.140
1674,Taiwan Province of China,2013,6.340,10.750,0.817,NaN,0.690,0.002,0.841,0.846,0.124
1675,Taiwan Province of China,2014,6.363,10.798,0.870,NaN,0.693,0.092,0.866,0.849,0.108
1676,Taiwan Province of China,2015,6.450,10.842,0.885,NaN,0.701,0.019,0.857,0.832,0.129
1677,Taiwan Province of China,2016,6.513,10.855,0.895,NaN,0.719,-0.049,0.811,0.833,0.108
1678,Taiwan Province of China,2017,6.359,10.871,0.891,NaN,0.760,-0.070,0.743,0.837,0.114

In [72]:
df[df["Country name"]=="Hong Kong S.A.R. of China"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
699,Hong Kong S.A.R. of China,2006,5.511,10.746,0.812,NaN,0.910,0.156,0.356,0.723,0.236
700,Hong Kong S.A.R. of China,2008,5.137,10.816,0.840,NaN,0.922,0.296,0.274,0.719,0.237
701,Hong Kong S.A.R. of China,2009,5.397,10.788,0.835,NaN,0.918,0.308,0.272,0.762,0.210
702,Hong Kong S.A.R. of China,2010,5.643,10.847,0.857,NaN,0.890,0.332,0.256,0.710,0.183
703,Hong Kong S.A.R. of China,2011,5.474,10.887,0.846,NaN,0.894,0.235,0.245,0.734,0.196
704,Hong Kong S.A.R. of China,2012,5.484,10.893,0.826,NaN,0.880,0.222,0.380,0.715,0.183
705,Hong Kong S.A.R. of China,2014,5.458,10.940,0.834,NaN,0.843,0.224,0.423,0.684,0.243
706,Hong Kong S.A.R. of China,2016,5.498,10.970,0.832,NaN,0.800,0.100,0.403,0.664,0.213
707,Hong Kong S.A.R. of China,2017,5.362,11.000,0.831,NaN,0.831,0.140,0.416,0.640,0.201
708,Hong Kong S.A.R. of China,2019,5.659,11.000,0.856,NaN,0.727,0.067,0.432,0.599,0.358

In [75]:
df[df["Country name"]=="Taiwan Province of China"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1669,Taiwan Province of China,2006,6.189,10.613,0.882,68.68,0.630,-0.030,0.846,0.814,0.094
1670,Taiwan Province of China,2008,5.548,10.606,0.830,69.14,0.642,-0.017,0.785,0.794,0.169
1671,Taiwan Province of China,2010,6.229,10.691,0.831,69.60,0.677,0.005,0.821,0.845,0.136
1672,Taiwan Province of China,2011,6.309,10.705,0.863,NaN,0.761,0.035,0.755,0.827,0.112
1673,Taiwan Province of China,2012,6.126,10.716,0.825,NaN,0.698,0.022,0.803,0.821,0.140
1674,Taiwan Province of China,2013,6.340,10.750,0.817,NaN,0.690,0.002,0.841,0.846,0.124
1675,Taiwan Province of China,2014,6.363,10.798,0.870,NaN,0.693,0.092,0.866,0.849,0.108
1676,Taiwan Province of China,2015,6.450,10.842,0.885,NaN,0.701,0.019,0.857,0.832,0.129
1677,Taiwan Province of China,2016,6.513,10.855,0.895,NaN,0.719,-0.049,0.811,0.833,0.108
1678,Taiwan Province of China,2017,6.359,10.871,0.891,NaN,0.760,-0.070,0.743,0.837,0.114

In [76]:
df[df["Country name"]=="Palestinian Territories"]

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1325,Palestinian Territories,2006,4.716,8.213,0.818,61.780,0.547,NaN,0.858,0.497,0.431
1326,Palestinian Territories,2007,4.151,8.218,0.712,61.897,0.365,-0.080,0.844,0.566,0.412
1327,Palestinian Territories,2008,4.386,8.276,0.666,62.015,0.358,-0.070,0.753,0.571,0.403
1328,Palestinian Territories,2009,4.470,8.329,0.738,62.132,0.468,-0.085,0.797,0.544,0.466
1329,Palestinian Territories,2010,4.703,8.383,0.822,62.250,0.504,-0.117,0.752,0.628,0.381
1330,Palestinian Territories,2011,4.751,8.474,0.751,NaN,0.522,-0.127,0.750,0.567,0.388
1331,Palestinian Territories,2012,4.647,8.531,0.782,NaN,0.542,-0.153,0.730,0.616,0.379
1332,Palestinian Territories,2013,4.844,8.489,0.761,NaN,0.454,-0.150,0.780,0.594,0.365
1333,Palestinian Territories,2014,4.722,8.457,0.775,NaN,0.657,-0.147,0.804,0.565,0.380
1334,Palestinian Territories,2015,4.695,8.480,0.766,NaN,0.556,-0.153,0.774,0.594,0.369
1335,Palestinian Territories,2016,4.907,8.498,0.818,NaN,0.608,-0.129,0.812,0.593,0.378
1336,Palestinian Territories,2017,4.628,8.485,0.824,NaN,0.632,-0.163,0.831,0.597,0.416

In [77]:
df = df[~((df['Country name'] == "Hong Kong S.A.R. of China") & 
    (df['Healthy life expectancy at birth'].isna()))]

In [78]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                    0
Social support                        0
Healthy life expectancy at birth     27
Freedom to make life choices         32
Generosity                           53
Perceptions of corruption           109
Positive affect                      22
Negative affect                      16
dtype: int64